Update python-publish.yml

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -1,39 +1,54 @@
-# This workflow will upload a Python Package using Twine when a release is created
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
-
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
-name: Upload Python Package
+name: Upload to PyPI
 
 on:
-  release:
-    types: [ published ]
-
-permissions:
-  contents: read
+  push:
+    tags:
+      - '*'
 
 jobs:
-  deploy:
-
+  build:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up Python
-        uses: actions/setup-python@v3
-        with:
-          python-version: '3.x'
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install build
-      - name: Build package
-        run: python -m build
-      - name: Publish package
-        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
-        with:
-          user: __token__
-          password: ${{ secrets.PYPI_API_TOKEN }}
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: 3.8
+
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install twine
+
+    - name: Build and upload to PyPI
+      env:
+        TWINE_USERNAME: __token__
+        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
+      run: |
+        export DXLIB_VERSION=$(python -c "import os; print(os.getenv('GITHUB_REF').split('/')[-1])")
+        python setup.py sdist bdist_wheel
+        twine check dist/*
+        
+        if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
+          tag="${{ github.ref/refs\/tags\// }}"
+        else
+          tag="test"
+        fi
+
+        if [[ "$tag" == "test" ]]; then
+          echo "Uploading to the test PyPI server..."
+          python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*$DXLIB_VERSION*
+          rm -rf dist/*.tar.gz
+          rm -rf dist/*.whl
+        elif [[ "$tag" == "prod" ]]; then
+          echo "Uploading to the production PyPI server..."
+          python -m twine upload dist/*$DXLIB_VERSION*
+          rm -rf dist/*.tar.gz
+          rm -rf dist/*.whl
+        else
+          echo "Invalid tag specified. Available options are 'test' or 'prod'."
+          exit 1
+        fi
